
export const digits = {
	'0': { href: 'digit.svg#d0', width: 6 },
	'1': { href: 'digit.svg#d1', width: 3 },
	'2': { href: 'digit.svg#d2', width: 7 },
	'3': { href: 'digit.svg#d3', width: 8 },
	'4': { href: 'digit.svg#d4', width: 5 },
	'5': { href: 'digit.svg#d5', width: 7 },
	'6': { href: 'digit.svg#d6', width: 7 },
	'7': { href: 'digit.svg#d7', width: 6 },
	'8': { href: 'digit.svg#d8', width: 6 },
	'9': { href: 'digit.svg#d9', width: 7 }
};

export const printed = {
	'А': { href: 'printed.svg#cA', width: 9 },
	'а': { href: 'printed.svg#sA', width: 6 },
	'Б': { href: 'printed.svg#cB', width: 7 },
	'б': { href: 'printed.svg#sB', width: 4 },
	'В': { href: 'printed.svg#cV', width: 8 },
	'в': { href: 'printed.svg#sV', width: 5 },
	'Г': { href: 'printed.svg#cGh', width: 5 },
	'г': { href: 'printed.svg#sGh', width: 3 },
	'Ґ': { href: 'printed.svg#cG', width: 6 },
	'ґ': { href: 'printed.svg#sG', width: 4 },
	'Д': { href: 'printed.svg#cD', width: 9 },
	'д': { href: 'printed.svg#sD', width: 6 },
	'Е': { href: 'printed.svg#cE', width: 6 },
	'е': { href: 'printed.svg#sE', width: 4 },
	'Є': { href: 'printed.svg#cJe', width: 8 },
	'є': { href: 'printed.svg#sJe', width: 5 },
	'Ж': { href: 'printed.svg#cZh', width: 11 },
	'ж': { href: 'printed.svg#sZh', width: 7 },
	'З': { href: 'printed.svg#cZ', width: 8 },
	'з': { href: 'printed.svg#sZ', width: 5 },
	'И': { href: 'printed.svg#cY', width: 7 },
	'и': { href: 'printed.svg#sY', width: 5 },
	'І': { href: 'printed.svg#cI', width: 2 },
	'і': { href: 'printed.svg#sI', width: 2 },
	'Ї': { href: 'printed.svg#cJi', width: 3 },
	'ї': { href: 'printed.svg#sJi', width: 3 },
	'Й': { href: 'printed.svg#cJ', width: 7 },
	'й': { href: 'printed.svg#sJ', width: 5 },
	'К': { href: 'printed.svg#cK', width: 7 },
	'к': { href: 'printed.svg#sK', width: 5 },
	'Л': { href: 'printed.svg#cL', width: 9 },
	'л': { href: 'printed.svg#sL', width: 5 },
	'М': { href: 'printed.svg#cM', width: 9 },
	'м': { href: 'printed.svg#sM', width: 7 },
	'Н': { href: 'printed.svg#cN', width: 7 },
	'н': { href: 'printed.svg#sN', width: 5 },
	'О': { href: 'printed.svg#cO', width: 9 },
	'о': { href: 'printed.svg#sO', width: 5 },
	'П': { href: 'printed.svg#cP', width: 7 },
	'п': { href: 'printed.svg#sP', width: 5 },
	'Р': { href: 'printed.svg#cR', width: 7 },
	'р': { href: 'printed.svg#sR', width: 5 },
	'С': { href: 'printed.svg#cS', width: 9 },
	'с': { href: 'printed.svg#sS', width: 7 },
	'Т': { href: 'printed.svg#cT', width: 8 },
	'т': { href: 'printed.svg#sT', width: 6 },
	'У': { href: 'printed.svg#cU', width: 7 },
	'у': { href: 'printed.svg#sU', width: 6 },
	'Ф': { href: 'printed.svg#cF', width: 9 },
	'ф': { href: 'printed.svg#sF', width: 7 },
	'Х': { href: 'printed.svg#cH', width: 9 },
	'х': { href: 'printed.svg#sH', width: 7 },
	'Ц': { href: 'printed.svg#cC', width: 8 },
	'ц': { href: 'printed.svg#sC', width: 6 },
	'Ч': { href: 'printed.svg#cCh', width: 7 },
	'ч': { href: 'printed.svg#sCh', width: 5 },
	'Ш': { href: 'printed.svg#cSh', width: 11 },
	'ш': { href: 'printed.svg#sSh', width: 7 },
	'Щ': { href: 'printed.svg#cSch', width: 12 },
	'щ': { href: 'printed.svg#sSch', width: 8 },
	'Ь': { href: 'printed.svg#cX', width: 7 },
	'ь': { href: 'printed.svg#sX', width: 5 },
	'Ю': { href: 'printed.svg#cJu', width: 9 },
	'ю': { href: 'printed.svg#sJu', width: 7 },
	'Я': { href: 'printed.svg#cJa', width: 7 },
	'я': { href: 'printed.svg#sJa', width: 5 },
};

export const cursive = {
	'А': { href: 'cursive.svg#cA', width: 8 },
	'а': { href: 'cursive.svg#sA', width: 6, kern: 0.5 },
	'Б': { href: 'cursive.svg#cB', width: 7 },
	'б': { href: 'cursive.svg#sB', width: 5, kern: 0.5 },
	'В': { href: 'cursive.svg#cV', width: 8 },
	'в': { href: 'cursive.svg#sV', width: 6 },
	'Г': { href: 'cursive.svg#cGh', width: 5 },
	'г': { href: 'cursive.svg#sGh', width: 4.5 },
	'Ґ': { href: 'cursive.svg#cG', width: 6 },
	'ґ': { href: 'cursive.svg#sG', width: 6 },
	'Д': { href: 'cursive.svg#cD', width: 9 },
	'д': { href: 'cursive.svg#sD', width: 6, kern: 1 },
	'Е': { href: 'cursive.svg#cE', width: 5 },
	'е': { href: 'cursive.svg#sE', width: 4.5 },
	'Є': { href: 'cursive.svg#cJe', width: 5.5 },
	'є': { href: 'cursive.svg#sJe', width: 3.5, kern: 1 },
	'Ж': { href: 'cursive.svg#cZh', width: 13 },
	'ж': { href: 'cursive.svg#sZh', width: 7 },
	'З': { href: 'cursive.svg#cZ', width: 7 },
	'з': { href: 'cursive.svg#sZ', width: 6.5, kern: 1.5 },
	'И': { href: 'cursive.svg#cY', width: 7.5 },
	'и': { href: 'cursive.svg#sY', width: 6, kern: 1 },
	'І': { href: 'cursive.svg#cI', width: 3.2 },
	'і': { href: 'cursive.svg#sI', width: 3, kern: 1 },
	'Ї': { href: 'cursive.svg#cJi', width: 3.2 },
	'ї': { href: 'cursive.svg#sJi', width: 3, kern: 1 },
	'Й': { href: 'cursive.svg#cJ', width: 7.3 },
	'й': { href: 'cursive.svg#sJ', width: 6, kern: 1 },
	'К': { href: 'cursive.svg#cK', width: 8.5 },
	'к': { href: 'cursive.svg#sK', width: 6, kern: 1 },
	'Л': { href: 'cursive.svg#cL', width: 7.5 },
	'л': { href: 'cursive.svg#sL', width: 6.5 },
	'М': { href: 'cursive.svg#cM', width: 11 },
	'м': { href: 'cursive.svg#sM', width: 8 },
	'Н': { href: 'cursive.svg#cN', width: 7.5 },
	'н': { href: 'cursive.svg#sN', width: 6.8, kern: 1.5 },
	'О': { href: 'cursive.svg#cO', width: 6 },
	'о': { href: 'cursive.svg#sO', width: 4 },
	'П': { href: 'cursive.svg#cP', width: 7.5 },
	'п': { href: 'cursive.svg#sP', width: 6.5, kern: 1 },
	'Р': { href: 'cursive.svg#cR', width: 5 },
	'р': { href: 'cursive.svg#sR', width: 7.5, kern: 2 },
	'С': { href: 'cursive.svg#cS', width: 4 },
	'с': { href: 'cursive.svg#sS', width: 3.5, kern: 1 },
	'Т': { href: 'cursive.svg#cT', width: 9.5 },
	'т': { href: 'cursive.svg#sT', width: 10, kern: 1.5 },
	'У': { href: 'cursive.svg#cU', width: 6 },
	'у': { href: 'cursive.svg#sU', width: 5.5, kern: 1 },
	'Ф': { href: 'cursive.svg#cF', width: 5 },
	'ф': { href: 'cursive.svg#sF', width: 5.5, kern: 0.5 },
	'Х': { href: 'cursive.svg#cH', width: 6 },
	'х': { href: 'cursive.svg#sH', width: 5.5 },
	'Ц': { href: 'cursive.svg#cC', width: 7.5 },
	'ц': { href: 'cursive.svg#sC', width: 6.5, kern: 0.8 },
	'Ч': { href: 'cursive.svg#cCh', width: 6.5 },
	'ч': { href: 'cursive.svg#sCh', width: 4.5 },
	'Ш': { href: 'cursive.svg#cSh', width: 10 },
	'ш': { href: 'cursive.svg#sSh', width: 7.5, kern: 1 },
	'Щ': { href: 'cursive.svg#cSch', width: 11 },
	'щ': { href: 'cursive.svg#sSch', width: 8.5, kern: 1 },
	'Ь': { href: 'cursive.svg#cX', width: 5 },
	'ь': { href: 'cursive.svg#sX', width: 2.5, kern: 0.5 },
	'Ъ': { href: 'cursive.svg#cXi', width: 5 },
	'ъ': { href: 'cursive.svg#sXi', width: 3.5, kern: 0.5 },
	'Ы': { href: 'cursive.svg#cYi', width: 7 },
	'ы': { href: 'cursive.svg#sYi', width: 6.5, kern: 1 },
	'Э': { href: 'cursive.svg#cEr', width: 5 },
	'э': { href: 'cursive.svg#sEr', width: 4 },
	'Ю': { href: 'cursive.svg#cJu', width: 9 },
	'ю': { href: 'cursive.svg#sJu', width: 6, kern: 1 },
	'Я': { href: 'cursive.svg#cJa', width: 8.5 },
	'я': { href: 'cursive.svg#sJa', width: 6 },
};

export const special = {
	'+': { href: 'special.svg#plus', width: 7 },
	'-': { href: 'special.svg#minus', width: 7 },
	'=': { href: 'special.svg#equal', width: 7 }
};
