
export const digits = {
	'0': { b: { href: 'digit.svg#d0', width: 6 } },
	'1': { b: { href: 'digit.svg#d1', width: 3 } },
	'2': { b: { href: 'digit.svg#d2', width: 7 } },
	'3': { b: { href: 'digit.svg#d3', width: 8 } },
	'4': { b: { href: 'digit.svg#d4', width: 5 } },
	'5': { b: { href: 'digit.svg#d5', width: 7 } },
	'6': { b: { href: 'digit.svg#d6', width: 7 } },
	'7': { b: { href: 'digit.svg#d7', width: 6 } },
	'8': { b: { href: 'digit.svg#d8', width: 6 } },
	'9': { b: { href: 'digit.svg#d9', width: 7  }}
};

export const printed = {
	'А': { b: { href: 'printed.svg#cA', width: 9 } },
	'а': { b: { href: 'printed.svg#sA', width: 6 } },
	'Б': { b: { href: 'printed.svg#cB', width: 7 } },
	'б': { b: { href: 'printed.svg#sB', width: 4 } },
	'В': { b: { href: 'printed.svg#cV', width: 8 } },
	'в': { b: { href: 'printed.svg#sV', width: 5 } },
	'Г': { b: { href: 'printed.svg#cGh', width: 5 } },
	'г': { b: { href: 'printed.svg#sGh', width: 3 } },
	'Ґ': { b: { href: 'printed.svg#cG', width: 6 } },
	'ґ': { b: { href: 'printed.svg#sG', width: 4 } },
	'Д': { b: { href: 'printed.svg#cD', width: 9 } },
	'д': { b: { href: 'printed.svg#sD', width: 6 } },
	'Е': { b: { href: 'printed.svg#cE', width: 6 } },
	'е': { b: { href: 'printed.svg#sE', width: 4 } },
	'Є': { b: { href: 'printed.svg#cJe', width: 8 } },
	'є': { b: { href: 'printed.svg#sJe', width: 5 } },
	'Ж': { b: { href: 'printed.svg#cZh', width: 11 } },
	'ж': { b: { href: 'printed.svg#sZh', width: 7 } },
	'З': { b: { href: 'printed.svg#cZ', width: 8 } },
	'з': { b: { href: 'printed.svg#sZ', width: 5 } },
	'И': { b: { href: 'printed.svg#cY', width: 7 } },
	'и': { b: { href: 'printed.svg#sY', width: 5 } },
	'І': { b: { href: 'printed.svg#cI', width: 2 } },
	'і': { b: { href: 'printed.svg#sI', width: 2 } },
	'Ї': { b: { href: 'printed.svg#cJi', width: 3 } },
	'ї': { b: { href: 'printed.svg#sJi', width: 3 } },
	'Й': { b: { href: 'printed.svg#cJ', width: 7 } },
	'й': { b: { href: 'printed.svg#sJ', width: 5 } },
	'К': { b: { href: 'printed.svg#cK', width: 7 } },
	'к': { b: { href: 'printed.svg#sK', width: 5 } },
	'Л': { b: { href: 'printed.svg#cL', width: 9 } },
	'л': { b: { href: 'printed.svg#sL', width: 5 } },
	'М': { b: { href: 'printed.svg#cM', width: 9 } },
	'м': { b: { href: 'printed.svg#sM', width: 7 } },
	'Н': { b: { href: 'printed.svg#cN', width: 7 } },
	'н': { b: { href: 'printed.svg#sN', width: 5 } },
	'О': { b: { href: 'printed.svg#cO', width: 9 } },
	'о': { b: { href: 'printed.svg#sO', width: 5 } },
	'П': { b: { href: 'printed.svg#cP', width: 7 } },
	'п': { b: { href: 'printed.svg#sP', width: 5 } },
	'Р': { b: { href: 'printed.svg#cR', width: 7 } },
	'р': { b: { href: 'printed.svg#sR', width: 5 } },
	'С': { b: { href: 'printed.svg#cS', width: 9 } },
	'с': { b: { href: 'printed.svg#sS', width: 7 } },
	'Т': { b: { href: 'printed.svg#cT', width: 8 } },
	'т': { b: { href: 'printed.svg#sT', width: 6 } },
	'У': { b: { href: 'printed.svg#cU', width: 7 } },
	'у': { b: { href: 'printed.svg#sU', width: 6 } },
	'Ф': { b: { href: 'printed.svg#cF', width: 9 } },
	'ф': { b: { href: 'printed.svg#sF', width: 7 } },
	'Х': { b: { href: 'printed.svg#cH', width: 9 } },
	'х': { b: { href: 'printed.svg#sH', width: 7 } },
	'Ц': { b: { href: 'printed.svg#cC', width: 8 } },
	'ц': { b: { href: 'printed.svg#sC', width: 6 } },
	'Ч': { b: { href: 'printed.svg#cCh', width: 7 } },
	'ч': { b: { href: 'printed.svg#sCh', width: 5 } },
	'Ш': { b: { href: 'printed.svg#cSh', width: 11 } },
	'ш': { b: { href: 'printed.svg#sSh', width: 7 } },
	'Щ': { b: { href: 'printed.svg#cSch', width: 12 } },
	'щ': { b: { href: 'printed.svg#sSch', width: 8 } },
	'Ь': { b: { href: 'printed.svg#cX', width: 7 } },
	'ь': { b: { href: 'printed.svg#sX', width: 5 } },
	'Ю': { b: { href: 'printed.svg#cJu', width: 9 } },
	'ю': { b: { href: 'printed.svg#sJu', width: 7 } },
	'Я': { b: { href: 'printed.svg#cJa', width: 7 } },
	'я': { b: { href: 'printed.svg#sJa', width: 5 } },
};

export const cursive = {
	'А': { b: { href: 'cursive.svg#cA', width: 8.5 } },
	'а': { b: { href: 'cursive.svg#sA', width: 6, kern: 0.6 } },
	'Б': { b: { href: 'cursive.svg#cB', width: 7 }, c: { href: 'cursive.svg#cB_', width: 7 } },
	'б': { b: { href: 'cursive.svg#sB', width: 5, kern: 0.5 }, c: { href: 'cursive.svg#sB_', width: 5, kern: 0.5 } },
	'В': { b: { href: 'cursive.svg#cV', width: 8 }, c: { href: 'cursive.svg#cV_', width: 7.5 } },
	'в': { b: { href: 'cursive.svg#sV', width: 5.5, kern: 0.2 }, c: { href: 'cursive.svg#sV_', width: 5.5, kern: 0.2 } },
	'Г': { b: { href: 'cursive.svg#cGh', width: 4.5 }, c: { href: 'cursive.svg#cGh_', width: 4.5 } },
	'г': { b: { href: 'cursive.svg#sGh', width: 4.5, kern: 0.3 } },
	'Ґ': { b: { href: 'cursive.svg#cG', width: 5 }, c: { href: 'cursive.svg#cG_', width: 5 } },
	'ґ': { b: { href: 'cursive.svg#sG', width: 4 }, c: { href: 'cursive.svg#sG_', width: 4 } },
	'Д': { b: { href: 'cursive.svg#cD', width: 9 } },
	'д': { b: { href: 'cursive.svg#sD', width: 6, kern: 0.8 } },
	'Е': { b: { href: 'cursive.svg#cE', width: 5 } },
	'е': { b: { href: 'cursive.svg#sE', width: 4.5 } },
	'Є': { b: { href: 'cursive.svg#cJe', width: 5.5 } },
	'є': { b: { href: 'cursive.svg#sJe', width: 4.1, kern: 1 } },
	'Ж': { b: { href: 'cursive.svg#cZh', width: 12.6 } },
	'ж': { b: { href: 'cursive.svg#sZh', width: 7.2 } },
	'З': { b: { href: 'cursive.svg#cZ', width: 6.5 }, c: { href: 'cursive.svg#cZ_', width: 6.5 } },
	'з': { b: { href: 'cursive.svg#sZ', width: 6.5, kern: 1.5 } },
	'И': { b: { href: 'cursive.svg#cY', width: 7.5 } },
	'и': { b: { href: 'cursive.svg#sY', width: 6, kern: 1 } },
	'І': { b: { href: 'cursive.svg#cI', width: 3.2 } },
	'і': { b: { href: 'cursive.svg#sI', width: 3, kern: 1 } },
	'Ї': { b: { href: 'cursive.svg#cJi', width: 3.2 } },
	'ї': { b: { href: 'cursive.svg#sJi', width: 3, kern: 1 } },
	'Й': { b: { href: 'cursive.svg#cJ', width: 7.3 } },
	'й': { b: { href: 'cursive.svg#sJ', width: 6, kern: 1 } },
	'К': { b: { href: 'cursive.svg#cK', width: 8.5 } },
	'к': { b: { href: 'cursive.svg#sK', width: 6, kern: 1 } },
	'Л': { b: { href: 'cursive.svg#cL', width: 7.2 } },
	'л': { b: { href: 'cursive.svg#sL', width: 6.2 } },
	'М': { b: { href: 'cursive.svg#cM', width: 11.2 } },
	'м': { b: { href: 'cursive.svg#sM', width: 8 } },
	'Н': { b: { href: 'cursive.svg#cN', width: 7.1 } },
	'н': { b: { href: 'cursive.svg#sN', width: 6.5, kern: 1.5 } },
	'О': { b: { href: 'cursive.svg#cO', width: 6 }, c: { href: 'cursive.svg#cO_', width: 6 } },
	'о': { b: { href: 'cursive.svg#sO', width: 4, kern: 0.7 }, c: { href: 'cursive.svg#sO_', width: 4.7, kern: 0.7 } },
	'П': { b: { href: 'cursive.svg#cP', width: 7.5 } },
	'п': { b: { href: 'cursive.svg#sP', width: 6.5, kern: 1 } },
	'Р': { b: { href: 'cursive.svg#cR', width: 5 }, c: { href: 'cursive.svg#cR_', width: 4.2 } },
	'р': { b: { href: 'cursive.svg#sR', width: 7.5, kern: 2.2 } },
	'С': { b: { href: 'cursive.svg#cS', width: 4.5 } },
	'с': { b: { href: 'cursive.svg#sS', width: 3.5, kern: 0.8 }, c: { href: 'cursive.svg#sS_', width: 4.3, kern: 0.8 } },
	'Т': { b: { href: 'cursive.svg#cT', width: 9.7 } },
	'т': { b: { href: 'cursive.svg#sT', width: 10, kern: 1.4 } },
	'У': { b: { href: 'cursive.svg#cU', width: 5.5 }, c: { href: 'cursive.svg#cU_', width: 5.5 } },
	'у': { b: { href: 'cursive.svg#sU', width: 5.5, kern: 0.8 } },
	'Ф': { b: { href: 'cursive.svg#cF', width: 4.1 }, c: { href: 'cursive.svg#cF_', width: 4.1 } },
	'ф': { b: { href: 'cursive.svg#sF', width: 6, kern: 0.4 }, c: { href: 'cursive.svg#sF_', width: 6, kern: 0.4 } },
	'Х': { b: { href: 'cursive.svg#cH', width: 6 } },
	'х': { b: { href: 'cursive.svg#sH', width: 5.5 } },
	'Ц': { b: { href: 'cursive.svg#cC', width: 7.5 } },
	'ц': { b: { href: 'cursive.svg#sC', width: 6.5, kern: 0.8 } },
	'Ч': { b: { href: 'cursive.svg#cCh', width: 6.4 } },
	'ч': { b: { href: 'cursive.svg#sCh', width: 5.1 } },
	'Ш': { b: { href: 'cursive.svg#cSh', width: 10 } },
	'ш': { b: { href: 'cursive.svg#sSh', width: 7.5, kern: 1 } },
	'Щ': { b: { href: 'cursive.svg#cSch', width: 11 } },
	'щ': { b: { href: 'cursive.svg#sSch', width: 8.5, kern: 1 } },
	'Ь': { b: { href: 'cursive.svg#cX', width: 4.6 }, c: { href: 'cursive.svg#cX_', width: 4.6 } },
	'ь': { b: { href: 'cursive.svg#sX', width: 3, kern: 0.5 }, c: { href: 'cursive.svg#sX_', width: 3.6, kern: 0.5 } },
	'Ъ': { b: { href: 'cursive.svg#cXi', width: 4.6 }, c: { href: 'cursive.svg#cXi_', width: 4.6 } },
	'ъ': { b: { href: 'cursive.svg#sXi', width: 4 }, c: { href: 'cursive.svg#sXi_', width: 4.7 } },
	'Ы': { b: { href: 'cursive.svg#cYi', width: 7 } },
	'ы': { b: { href: 'cursive.svg#sYi', width: 6.5, kern: 1 } },
	'Э': { b: { href: 'cursive.svg#cEr', width: 5.3 }, c: { href: 'cursive.svg#cEr_', width: 5.3 } },
	'э': { b: { href: 'cursive.svg#sEr', width: 4 }, c: { href: 'cursive.svg#sEr_', width: 4.2 } },
	'Ю': { b: { href: 'cursive.svg#cJu', width: 8.7 }, c: { href: 'cursive.svg#cJu_', width: 8.7 } },
	'ю': { b: { href: 'cursive.svg#sJu', width: 6.4, kern: 1 }, c: { href: 'cursive.svg#sJu_', width: 6.6, kern: 1 } },
	'Я': { b: { href: 'cursive.svg#cJa', width: 8.6 } },
	'я': { b: { href: 'cursive.svg#sJa', width: 5.8 } },
};

export const samples = {
	'А': 'images/img1.jpg',
	'Б': 'images/img2.jpg',
	'В': 'images/img3.jpg',
	'Г': 'images/img4.jpg',
	'Ґ': 'images/img5.jpg',
	'Д': 'images/img6.jpg',
	'Е': 'images/img7.jpg',
	'Ё': 'images/img8.jpg',
	'Ж': 'images/img9.jpg',
	'З': 'images/img10.jpg',
	'И': 'images/img11.jpg',
	'Й': 'images/img12.jpg',
	'К': 'images/img13.jpg',
	'Л': 'images/img14.jpg',
	'М': 'images/img15.jpg',
	'Н': 'images/img16.jpg',
	'О': 'images/img17.jpg',
	'П': 'images/img18.jpg',
	'Р': 'images/img19.jpg',
	'С': 'images/img20.jpg',
	'Т': 'images/img21.jpg',
	'У': 'images/img22.jpg',
	'Ф': 'images/img23.jpg',
	'Х': 'images/img24.jpg',
	'Ц': 'images/img25.jpg',
	'Ч': 'images/img26.jpg',
	'Ш': 'images/img27.jpg',
	'Щ': 'images/img28.jpg',
	'Ъ': 'images/img29.jpg',
	'Ы': 'images/img30.jpg',
	'Ь': 'images/img31.jpg',
	'Э': 'images/img32.jpg',
	'Ю': 'images/img33.jpg',
	'Я': 'images/img34.jpg',
	'І': 'images/img35.jpg',
	'Ї': 'images/img36.jpg',
};

export const special = {
	'+': { b: { href: 'special.svg#plus', width: 7 } },
	'-': { b: { href: 'special.svg#minus', width: 7 } },
	'=': { b: { href: 'special.svg#equal', width: 7 } },
	'.': { b: { href: 'special.svg#dot', width: 4 } },
	',': { b: { href: 'special.svg#comma', width: 4 } },
	'!': { b: { href: 'special.svg#exclamation', width: 6 } },
	'?': { b: { href: 'special.svg#question', width: 8 } },
	':': { b: { href: 'special.svg#colon', width: 4 } },
	';': { b: { href: 'special.svg#semicolon', width: 4 } },
};
